#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cp -f $__dir/../package.json $__dir/../distributable/package.json
cd $__dir/../; npm run tsc-carflip
